// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JhIRFhgEaHIbo2h0zHnqZ7zVfXgKFWU',
    appId: '1:255093586479:web:f0b15cc077359e039324da',
    messagingSenderId: '255093586479',
    projectId: 'reservasports-84819',
    authDomain: 'reservasports-84819.firebaseapp.com',
    storageBucket: 'reservasports-84819.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6UiCnxi34tft8-xS8J3E6ViBGZVj1xE4',
    appId: '1:255093586479:android:671f269e471676839324da',
    messagingSenderId: '255093586479',
    projectId: 'reservasports-84819',
    storageBucket: 'reservasports-84819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu88_FKDli-O92XeSYOAgt7-DscZJTsxg',
    appId: '1:255093586479:ios:e28c7e30c9b627669324da',
    messagingSenderId: '255093586479',
    projectId: 'reservasports-84819',
    storageBucket: 'reservasports-84819.firebasestorage.app',
    iosBundleId: 'com.example.canchaMovil',
  );

}